PERT_SCRATCH: tmp
prel_coms:
    - module load perturbo
    - module load qe
comp_info:
    scf: 
        exec: srun -n 64 pw.x -npools 8
    phonon:
        exec: srun -n 64 ph.x -npools 8
    nscf:
        exec: srun -n 64 pw.x -npools 8
    wannier90:
        exec: srun -n 2 wannier90.x
    pw2wannier90:
        exec: srun -n 1 pw2wannier90.x
    qe2pert:
        prel_coms:
            - export OMP_NUM_THREADS=8
        exec: srun -n 8 qe2pert.x -npools 8
    perturbo:
        prel_coms:
            - export OMP_NUM_THREADS=8
        exec: srun -n 8 perturbo.x -npools 8
